import EventBus from '../core/EventBus.js';import GameState from '../core/GameState.js';import ProvablyFair from '../core/ProvablyFair.js';import ProfileManager from '../core/ProfileManager.js';
import WearSystem from '../economy/WearSystem.js';import CaseSystem from '../economy/CaseSystem.js';import InventorySystem from '../economy/InventorySystem.js';import MarketSystem from '../economy/MarketSystem.js';import RankSystem from '../economy/RankSystem.js';import PrestigeSystem from '../economy/PrestigeSystem.js';import TournamentSystem from '../economy/TournamentSystem.js';import AchievementSystem from '../economy/AchievementSystem.js';import BehaviorSystem from '../economy/BehaviorSystem.js';import StatsSystem from '../economy/StatsSystem.js';
import CasinoManager from '../casino/CasinoManager.js';import SkinRenderer from '../graphics/SkinRenderer.js';import CaseRenderer from '../graphics/CaseRenderer.js';import BackgroundEngine from '../graphics/BackgroundEngine.js';import ParticleEngine from '../graphics/ParticleEngine.js';import Components from './Components.js';

export default class UIController{constructor(config={page:'index'}){this.page=config.page}init(){this.bus=new EventBus();this.state=new GameState();this.state.init();this.pf=new ProvablyFair({state:this.state});this.profile=new ProfileManager({state:this.state});this.wear=new WearSystem();this.inv=new InventorySystem({state:this.state});this.caseSys=new CaseSystem({state:this.state,wear:this.wear,inventory:this.inv});this.market=new MarketSystem({state:this.state});this.rank=new RankSystem();this.prestige=new PrestigeSystem({state:this.state});this.tour=new TournamentSystem({state:this.state});this.ach=new AchievementSystem({state:this.state});this.beh=new BehaviorSystem({state:this.state});this.stats=new StatsSystem({state:this.state});this.casino=new CasinoManager({pf:this.pf,stats:this.stats});this.skinR=new SkinRenderer();this.caseR=new CaseRenderer();this.ui=new Components();[this.wear,this.caseSys,this.market,this.rank,this.prestige,this.tour,this.ach,this.beh,this.stats,this.casino,this.skinR,this.caseR,this.ui].forEach(m=>m.init());this.bg=new BackgroundEngine({canvas:document.getElementById('bgCanvas')});this.fx=new ParticleEngine({canvas:document.getElementById('bgCanvas')});this.bg.init();this.fx.init();this.activateNav();this.render()}update(){this.beh.classify()}destroy(){[this.state,this.market,this.casino,this.bg,this.fx].forEach(m=>m.destroy&&m.destroy())}
activateNav(){document.querySelector(`[data-nav='${this.page}']`)?.classList.add('active')}
header(){const s=this.state.get();const r=this.rank.get(s.level);return `<div class='grid g3'>${this.ui.stat('Wallet','$'+s.wallet.toFixed(2))}${this.ui.stat('Vault','$'+s.vault.toFixed(2))}${this.ui.stat('Rank',r)}</div><div class='panel'>XP<div class='progress'><span style='width:${s.xp%100}%'></span></div></div>`}
render(){this.update();const root=document.getElementById('app');const s=this.state.get();const pages={
index:()=>`${this.header()}<div class='grid g3'>${this.ui.stat('Prestige',s.prestige)}${this.ui.stat('Session P/L','$'+(s.wallet-s.session.startWallet).toFixed(2))}${this.ui.stat('Inventory','$'+this.inv.value().toFixed(2))}</div><div class='panel'>Daily mission: ${s.missions.daily} • streak: ${s.missions.streak}</div>`,
cases:()=>`${this.header()}<div class='panel'>Odds ${this.caseSys.odds().map(o=>o.name+': '+o.pct+'%').join(' | ')}</div><div class='cards'>${this.caseSys.cases.map(c=>`<div class='card'>${this.caseR.render(c.name)}<div class='row'><b>${c.name}</b><span>$${c.price}</span></div><div class='tabs'><button class='btn-primary' data-open='${c.id},1'>x1</button><button class='btn-secondary' data-open='${c.id},5'>x5</button><button class='btn-secondary' data-open='${c.id},10'>x10</button></div></div>`).join('')}</div>`,
inventory:()=>`${this.header()}<div class='panel row'><div>Total: $${this.inv.value().toFixed(2)}</div><button class='btn-danger' id='sellAll'>Sell all</button></div><div class='cards'>${s.inventory.map((i,n)=>`<div class='card rarity-${i.rarity.toLowerCase().replace(/ /g,'-')}'><b>${i.name}</b>${this.skinR.render(i)}<div>${i.rarity} • ${i.wear} • float ${i.float}</div><div class='row'><span>$${i.value}</span><button class='btn-secondary' data-sell='${n}'>Sell</button></div></div>`).join('')}</div>`,
market:()=>`${this.header()}<div class='panel'>Market tick 5s • GBM μ=0.0002, σ=0.02–0.08</div><div class='panel'><table class='table'><thead><tr><th>Asset</th><th>Price</th><th>Spread</th><th>Vol</th><th>Trade</th></tr></thead><tbody>${Object.entries(s.market).slice(0,40).map(([id,m])=>`<tr><td>Skin-${id}</td><td>$${m.price}</td><td>${(m.spread*100).toFixed(2)}%</td><td>${m.vol.toFixed(3)}</td><td><button class='btn-secondary' data-buy='${id}'>Buy</button> <button class='btn-danger' data-sellm='${id}'>Sell</button></td></tr>`).join('')}</tbody></table></div>`,
casino:()=>`${this.header()}<div class='tabs'>${Object.keys(this.casino.games).map(g=>`<button class='btn-secondary' data-game='${g}'>${g}</button>`).join('')}</div><div class='panel'><div id='gameInfo'>Transparent odds. Outcome is fixed before animation via SHA-256 seed hash.</div><div class='row'><input id='bet' type='number' value='5' min='1'/><button class='btn-primary' id='play'>Play</button></div><pre id='out'></pre></div>`,
skill:()=>`${this.header()}<div class='panel'><button class='btn-primary' id='startSkill'>Start 30s skill run</button><div id='skillArena' style='height:260px;border:1px solid var(--border);margin-top:8px;position:relative'></div><div id='skillStat'></div></div>`,
tournaments:()=>`${this.header()}<div class='panel'><table class='table'><tbody>${this.tour.leaderboard().map((r,i)=>`<tr><td>#${i+1}</td><td>${r.name}</td><td>${r.pts}</td></tr>`).join('')}</tbody></table></div>`,
vault:()=>`${this.header()}<div class='grid g2'><div class='panel'><input id='dep' type='number' value='10'/><button class='btn-success' id='deposit'>Deposit</button></div><div class='panel'><input id='wd' type='number' value='10'/><button class='btn-secondary' id='withdraw'>Withdraw</button></div></div>`,
achievements:()=>`${this.header()}<div class='cards'>${this.ach.progress().map(a=>`<div class='card ${a.done?'rarity-rare-special':''}'><b>${a.name}</b><div>${a.done?'Unlocked':'Locked'}</div><div class='progress'><span style='width:${Math.min(100,s.stats.wagered/a.target*100)}%'></span></div></div>`).join('')}</div>`,
profile:()=>`${this.header()}<div class='grid g3'>${this.ui.stat('Behavior',s.behavior.type)}${this.ui.stat('Wagered','$'+s.stats.wagered.toFixed(2))}${this.ui.stat('Biggest win','$'+s.stats.biggestWin.toFixed(2))}</div><div class='panel'>RTP curve</div><canvas id='rtpChart' width='700' height='130'></canvas><div class='panel'><button class='btn-primary' id='share'>Export stat card PNG</button><canvas id='card' width='420' height='220'></canvas></div>`,
settings:()=>`${this.header()}<div class='panel'>Seeds: ${s.provablyFair.clientSeed} / ${s.provablyFair.serverSeed} / nonce ${s.provablyFair.nonce}</div><div class='tabs'><button class='btn-secondary' id='regen'>Regenerate seeds</button><button class='btn-success' id='export'>Export profile</button><button class='btn-danger' id='reset'>Reset</button></div><textarea id='json' rows='8'></textarea><button class='btn-secondary' id='import'>Import JSON</button>`
};root.innerHTML=pages[this.page]?pages[this.page]():'<div class="panel">Unknown page</div>';this.bind();if(this.page==='profile')this.drawRTP()}
bind(){const q=s=>document.querySelector(s),s=this.state.get();
if(this.page==='cases')document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const [id,c]=b.dataset.open.split(',').map(Number);this.caseSys.open(id,c);this.render()});
if(this.page==='inventory'){q('#sellAll')?.addEventListener('click',()=>{this.inv.sellAll();this.render()});document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>{this.inv.sell(+b.dataset.sell);this.render()})}
if(this.page==='market'){document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{this.market.trade(+b.dataset.buy,1,true);this.render()});document.querySelectorAll('[data-sellm]').forEach(b=>b.onclick=()=>{this.market.trade(+b.dataset.sellm,1,false);this.render()})}
if(this.page==='casino'){let g='blackjack';document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{g=b.dataset.game;q('#gameInfo').textContent=`${g} edge ${(this.casino.get(g).edge*100).toFixed(2)}%`});q('#play')?.addEventListener('click',async()=>{const bet=Math.max(1,+q('#bet').value||1);if(s.wallet<bet)return;const chance={blackjack:.492,roulette:18/37,crash:.485,mines:.47,dice:.495,plinko:.46,slots:.42,coinflip:.495,jackpot:.32}[g]||.5;const r=await this.casino.get(g).play(bet,chance);q('#out').textContent=JSON.stringify(r,null,2);this.state.patch(st=>{st.xp+=4;st.tournament.points+=Math.max(0,Math.round(r.payout-bet))});this.render()})}
if(this.page==='skill')q('#startSkill')?.addEventListener('click',()=>{const arena=q('#skillArena'),txt=q('#skillStat');arena.innerHTML='';let t=30,hit=0,shots=0;const int=setInterval(()=>{t--;shots++;const d=document.createElement('div');d.style.cssText=`position:absolute;width:20px;height:20px;border-radius:50%;background:#a855f7;left:${Math.random()*95}%;top:${Math.random()*90}%;cursor:pointer`;d.onclick=()=>{hit++;d.remove()};arena.appendChild(d);setTimeout(()=>d.remove(),800);txt.textContent=`${t}s hit ${hit}/${shots}`;if(t<=0){clearInterval(int);const acc=hit/Math.max(1,shots),rew=+(hit*0.8*acc).toFixed(2);this.state.patch(st=>{st.wallet+=rew;st.xp+=hit;st.tournament.points+=Math.round(rew*2)});this.render()}},1000)});
if(this.page==='vault'){q('#deposit')?.addEventListener('click',()=>{this.state.patch(st=>{const v=+q('#dep').value||0;if(st.wallet>=v){st.wallet-=v;st.vault+=v}});this.render()});q('#withdraw')?.addEventListener('click',()=>{this.state.patch(st=>{const v=+q('#wd').value||0;if(st.vault>=v){st.vault-=v;st.wallet+=v}});this.render()})}
if(this.page==='profile')q('#share')?.addEventListener('click',()=>{const c=q('#card'),x=c.getContext('2d');x.fillStyle='#0c0c12';x.fillRect(0,0,c.width,c.height);x.fillStyle='#c084fc';x.font='bold 18px sans-serif';x.fillText('CCR Profile Card',16,30);x.fillStyle='#f1f1f5';x.fillText(`User: ${s.profile.username}`,16,62);x.fillText(`Behavior: ${s.behavior.type}`,16,90);x.fillText(`Profit: $${s.stats.profit.toFixed(2)}`,16,118);x.fillText(`Rares: ${s.stats.rareDrops}`,16,146);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='ccr-card.png';a.click()});
if(this.page==='settings'){q('#regen')?.addEventListener('click',()=>{this.pf.regen();this.render()});q('#export')?.addEventListener('click',()=>{q('#json').value=this.profile.export()});q('#import')?.addEventListener('click',()=>{this.profile.import(q('#json').value)});q('#reset')?.addEventListener('click',()=>{localStorage.removeItem('ccr2_state');location.reload()})}}
drawRTP(){const c=document.getElementById('rtpChart');if(!c)return;const x=c.getContext('2d');const v=this.state.get().stats.rtpSeries;if(!v.length)return;x.clearRect(0,0,c.width,c.height);x.strokeStyle='#9d4edd';x.beginPath();v.forEach((n,i)=>{const y=120-(n/150)*110;x[i?'lineTo':'moveTo']((i/Math.max(1,v.length-1))*c.width,y)});x.stroke()}}
